server:
  error:
    include-message: always
  port: ${COMMON_PORT}
spring:
  application:
    name: spring-js
  mvc:
    log-resolved-exception: true
  servlet:
    multipart:
      resolve-lazily: true
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}/auth/realms/${REALM}
keycloak:
  realm: ${REALM}
  auth-server-url: ${KEYCLOAK_HOST}/auth
  resource: ${KEYCLOAK_CLIENT}
  public-client: true
auth:
  admin:
    username: ${KEYCLOAK_ADMIN_USER}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
common:
  keycloak:
    token-uri: ${KEYCLOAK_HOST}/auth/realms/${REALM}/protocol/openid-connect/token



