
POSTGRES_USER: sweeft
POSTGRES_PASSWORD: sweeft
POSTGRES_URL: jdbc:postgresql://localhost:5432/common


REALM: sweeft
KEYCLOAK_HOST: http://localhost:8081
KEYCLOAK_ADMIN_USER: admin
KEYCLOAK_ADMIN_PASSWORD: admin
KEYCLOAK_CLIENT: sweeft-api-gateway

COMMON_PORT: 8080